#!/usr/bin/env ruby
#^syntax detection
#
# Copyright 2013 Ian Kenney
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
#
site 'http://community.opscode.com/api/v1'
cookbook 'apt'
cookbook 'vim'
cookbook 'tmux'
cookbook 'git'
cookbook 'build-essential'
cookbook 'curl'
cookbook 'openssl'
cookbook 'database'
cookbook 'postgresql'
cookbook 'rvm', git: 'https://github.com/fnichol/chef-rvm.git'
#cookbook 'chef-heroku-toolbelt', git: 'https://github.com/jimeh/chef-heroku-toolbelt.git'
cookbook 'heroku-toolbelt', git: 'https://github.com/ikenney/heroku-toolbelt.git'
cookbook 'dotmatrix', git: 'https://github.com/ikenney/dotmatrix.git'

